name: CI
on: [push, pull_request]

jobs:
  node-20-typescript:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: git diff --exit-code
